/**
 * Firebase Seeding Script
 * Run with: npx ts-node src/seedData.ts
 *
 * Seeds Firestore with 2026 F1 season data:
 * - 20 drivers with pricing
 * - 10 constructors with pricing
 * - 24 races (full calendar)
 * - Season configuration
 */

import * as admin from 'firebase-admin';
import * as path from 'path';

// Initialize Firebase Admin with service account
const serviceAccountPath = path.join(__dirname, '../serviceAccountKey.json');

try {
  const serviceAccount = require(serviceAccountPath);
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
  });
  console.log('Firebase Admin initialized successfully');
} catch (error) {
  console.error('Error: Could not find serviceAccountKey.json');
  console.log('\nTo get your service account key:');
  console.log('1. Go to Firebase Console > Project Settings > Service Accounts');
  console.log('2. Click "Generate new private key"');
  console.log('3. Save the file as "serviceAccountKey.json" in the functions/ folder');
  process.exit(1);
}

const db = admin.firestore();

// ============================================
// 2026 Driver Data
// ============================================
const drivers = [
  // A-Tier Drivers (price > 200)
  {
    id: 'norris',
    name: 'Lando Norris',
    shortName: 'NOR',
    number: 1,
    constructorId: 'mclaren',
    constructorName: 'McLaren F1 Team',
    nationality: 'British',
    price: 423,
    previousPrice: 400,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'A',
    isActive: true,
  },
  {
    id: 'verstappen',
    name: 'Max Verstappen',
    shortName: 'VER',
    number: 1,
    constructorId: 'red_bull',
    constructorName: 'Oracle Red Bull Racing',
    nationality: 'Dutch',
    price: 421,
    previousPrice: 400,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'A',
    isActive: true,
  },
  {
    id: 'piastri',
    name: 'Oscar Piastri',
    shortName: 'PIA',
    number: 81,
    constructorId: 'mclaren',
    constructorName: 'McLaren F1 Team',
    nationality: 'Australian',
    price: 410,
    previousPrice: 380,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'A',
    isActive: true,
  },
  {
    id: 'russell',
    name: 'George Russell',
    shortName: 'RUS',
    number: 63,
    constructorId: 'mercedes',
    constructorName: 'Mercedes-AMG Petronas F1 Team',
    nationality: 'British',
    price: 319,
    previousPrice: 300,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'A',
    isActive: true,
  },
  {
    id: 'leclerc',
    name: 'Charles Leclerc',
    shortName: 'LEC',
    number: 16,
    constructorId: 'ferrari',
    constructorName: 'Scuderia Ferrari',
    nationality: 'Monegasque',
    price: 242,
    previousPrice: 230,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'A',
    isActive: true,
  },
  // B-Tier Drivers (price < 200)
  {
    id: 'hamilton',
    name: 'Lewis Hamilton',
    shortName: 'HAM',
    number: 44,
    constructorId: 'ferrari',
    constructorName: 'Scuderia Ferrari',
    nationality: 'British',
    price: 156,
    previousPrice: 160,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'antonelli',
    name: 'Kimi Antonelli',
    shortName: 'ANT',
    number: 12,
    constructorId: 'mercedes',
    constructorName: 'Mercedes-AMG Petronas F1 Team',
    nationality: 'Italian',
    price: 150,
    previousPrice: 140,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'albon',
    name: 'Alexander Albon',
    shortName: 'ALB',
    number: 23,
    constructorId: 'williams',
    constructorName: 'Williams Racing',
    nationality: 'Thai-British',
    price: 73,
    previousPrice: 70,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'sainz',
    name: 'Carlos Sainz Jr.',
    shortName: 'SAI',
    number: 55,
    constructorId: 'williams',
    constructorName: 'Williams Racing',
    nationality: 'Spanish',
    price: 64,
    previousPrice: 60,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'alonso',
    name: 'Fernando Alonso',
    shortName: 'ALO',
    number: 14,
    constructorId: 'aston_martin',
    constructorName: 'Aston Martin Aramco F1 Team',
    nationality: 'Spanish',
    price: 56,
    previousPrice: 55,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'hulkenberg',
    name: 'Nico Hulkenberg',
    shortName: 'HUL',
    number: 27,
    constructorId: 'sauber',
    constructorName: 'Stake F1 Team Kick Sauber',
    nationality: 'German',
    price: 51,
    previousPrice: 50,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'hadjar',
    name: 'Isack Hadjar',
    shortName: 'HAD',
    number: 6,
    constructorId: 'red_bull',
    constructorName: 'Oracle Red Bull Racing',
    nationality: 'French',
    price: 51,
    previousPrice: 50,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'bearman',
    name: 'Oliver Bearman',
    shortName: 'BEA',
    number: 87,
    constructorId: 'haas',
    constructorName: 'MoneyGram Haas F1 Team',
    nationality: 'British',
    price: 41,
    previousPrice: 40,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'lawson',
    name: 'Liam Lawson',
    shortName: 'LAW',
    number: 30,
    constructorId: 'racing_bulls',
    constructorName: 'Racing Bulls',
    nationality: 'New Zealand',
    price: 38,
    previousPrice: 35,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'ocon',
    name: 'Esteban Ocon',
    shortName: 'OCO',
    number: 31,
    constructorId: 'haas',
    constructorName: 'MoneyGram Haas F1 Team',
    nationality: 'French',
    price: 38,
    previousPrice: 35,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'stroll',
    name: 'Lance Stroll',
    shortName: 'STR',
    number: 18,
    constructorId: 'aston_martin',
    constructorName: 'Aston Martin Aramco F1 Team',
    nationality: 'Canadian',
    price: 33,
    previousPrice: 30,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'gasly',
    name: 'Pierre Gasly',
    shortName: 'GAS',
    number: 10,
    constructorId: 'alpine',
    constructorName: 'BWT Alpine F1 Team',
    nationality: 'French',
    price: 22,
    previousPrice: 20,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  {
    id: 'bortoleto',
    name: 'Gabriel Bortoleto',
    shortName: 'BOR',
    number: 5,
    constructorId: 'sauber',
    constructorName: 'Stake F1 Team Kick Sauber',
    nationality: 'Brazilian',
    price: 19,
    previousPrice: 20,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: true,
  },
  // Drivers with 0 price (reserve/unconfirmed seats)
  {
    id: 'lindblad',
    name: 'Arvid Lindblad',
    shortName: 'LIN',
    number: 0,
    constructorId: 'racing_bulls',
    constructorName: 'Racing Bulls',
    nationality: 'British',
    price: 0,
    previousPrice: 0,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: false,
  },
  {
    id: 'colapinto',
    name: 'Franco Colapinto',
    shortName: 'COL',
    number: 43,
    constructorId: 'alpine',
    constructorName: 'BWT Alpine F1 Team',
    nationality: 'Argentinian',
    price: 0,
    previousPrice: 0,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: false,
  },
  {
    id: 'perez',
    name: 'Sergio Perez',
    shortName: 'PER',
    number: 11,
    constructorId: 'cadillac',
    constructorName: 'Cadillac F1',
    nationality: 'Mexican',
    price: 0,
    previousPrice: 0,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: false,
  },
  {
    id: 'bottas',
    name: 'Valtteri Bottas',
    shortName: 'BOT',
    number: 77,
    constructorId: 'cadillac',
    constructorName: 'Cadillac F1',
    nationality: 'Finnish',
    price: 0,
    previousPrice: 0,
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: 'B',
    isActive: false,
  },
];

// ============================================
// 2026 Constructor Data
// ============================================
const constructors = [
  {
    id: 'mclaren',
    name: 'McLaren F1 Team',
    shortName: 'MCL',
    nationality: 'British',
    teamPrincipal: 'Andrea Stella',
    primaryColor: '#FF8000',
    secondaryColor: '#47C7FC',
    price: 400,
    previousPrice: 400,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['norris', 'piastri'],
    isActive: true,
  },
  {
    id: 'mercedes',
    name: 'Mercedes-AMG Petronas F1 Team',
    shortName: 'MER',
    nationality: 'German',
    teamPrincipal: 'Toto Wolff',
    primaryColor: '#27F4D2',
    secondaryColor: '#000000',
    price: 258,
    previousPrice: 258,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['russell', 'antonelli'],
    isActive: true,
  },
  {
    id: 'red_bull',
    name: 'Oracle Red Bull Racing',
    shortName: 'RBR',
    nationality: 'Austrian',
    teamPrincipal: 'Laurent Mekies',
    primaryColor: '#3671C6',
    secondaryColor: '#FFD700',
    price: 251,
    previousPrice: 251,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['verstappen', 'hadjar'],
    isActive: true,
  },
  {
    id: 'ferrari',
    name: 'Scuderia Ferrari',
    shortName: 'FER',
    nationality: 'Italian',
    teamPrincipal: 'Fred Vasseur',
    primaryColor: '#E80020',
    secondaryColor: '#FFEB00',
    price: 230,
    previousPrice: 230,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['leclerc', 'hamilton'],
    isActive: true,
  },
  {
    id: 'williams',
    name: 'Williams Racing',
    shortName: 'WIL',
    nationality: 'British',
    teamPrincipal: 'James Vowles',
    primaryColor: '#64C4FF',
    secondaryColor: '#00A3E0',
    price: 128,
    previousPrice: 128,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['sainz', 'albon'],
    isActive: true,
  },
  {
    id: 'racing_bulls',
    name: 'Racing Bulls',
    shortName: 'RB',
    nationality: 'Italian',
    teamPrincipal: 'Alan Permane',
    primaryColor: '#6692FF',
    secondaryColor: '#1E5BC6',
    price: 111,
    previousPrice: 111,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['lawson', 'lindblad'],
    isActive: true,
  },
  {
    id: 'aston_martin',
    name: 'Aston Martin Aramco F1 Team',
    shortName: 'AMR',
    nationality: 'British',
    teamPrincipal: 'Adrian Newey',
    primaryColor: '#229971',
    secondaryColor: '#CEDC00',
    price: 110,
    previousPrice: 110,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['alonso', 'stroll'],
    isActive: true,
  },
  {
    id: 'haas',
    name: 'MoneyGram Haas F1 Team',
    shortName: 'HAA',
    nationality: 'American',
    teamPrincipal: 'Ayao Komatsu',
    primaryColor: '#B6BABD',
    secondaryColor: '#E10600',
    price: 106,
    previousPrice: 106,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['ocon', 'bearman'],
    isActive: true,
  },
  {
    id: 'sauber',
    name: 'Stake F1 Team Kick Sauber',
    shortName: 'SAU',
    nationality: 'Swiss',
    teamPrincipal: 'Jonathan Wheatley',
    primaryColor: '#52E252',
    secondaryColor: '#000000',
    price: 102,
    previousPrice: 102,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['hulkenberg', 'bortoleto'],
    isActive: true,
  },
  {
    id: 'alpine',
    name: 'BWT Alpine F1 Team',
    shortName: 'ALP',
    nationality: 'French',
    teamPrincipal: 'Flavio Briatore',
    primaryColor: '#FF87BC',
    secondaryColor: '#0093CC',
    price: 84,
    previousPrice: 84,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['gasly', 'colapinto'],
    isActive: true,
  },
  {
    id: 'cadillac',
    name: 'Cadillac F1',
    shortName: 'CAD',
    nationality: 'American',
    teamPrincipal: 'Graeme Lowdon',
    primaryColor: '#524E4E',
    secondaryColor: '#000000',
    price: 75,
    previousPrice: 75,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['bottas', 'perez'],
    isActive: true,
  },
];

// ============================================
// 2026 Race Calendar
// ============================================
const races = [
  {
    id: 'australia_2026',
    seasonId: '2026',
    round: 1,
    name: 'Australian Grand Prix',
    officialName: 'Formula 1 Rolex Australian Grand Prix 2026',
    circuitId: 'albert_park',
    circuitName: 'Albert Park Circuit',
    country: 'Australia',
    city: 'Melbourne',
    timezone: 'Australia/Melbourne',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-03-06T01:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-03-06T05:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-03-07T01:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-03-07T05:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-03-08T04:00:00Z')),
    },
  },
  {
    id: 'china_2026',
    seasonId: '2026',
    round: 2,
    name: 'Chinese Grand Prix',
    officialName: 'Formula 1 Lenovo Chinese Grand Prix 2026',
    circuitId: 'shanghai',
    circuitName: 'Shanghai International Circuit',
    country: 'China',
    city: 'Shanghai',
    timezone: 'Asia/Shanghai',
    hasSprint: true,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-03-13T03:30:00Z')),
      sprintQualifying: admin.firestore.Timestamp.fromDate(new Date('2026-03-13T07:30:00Z')),
      sprint: admin.firestore.Timestamp.fromDate(new Date('2026-03-14T03:00:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-03-14T07:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-03-15T07:00:00Z')),
    },
  },
  {
    id: 'japan_2026',
    seasonId: '2026',
    round: 3,
    name: 'Japanese Grand Prix',
    officialName: 'Formula 1 Lenovo Japanese Grand Prix 2026',
    circuitId: 'suzuka',
    circuitName: 'Suzuka International Racing Course',
    country: 'Japan',
    city: 'Suzuka',
    timezone: 'Asia/Tokyo',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-03-27T02:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-03-27T06:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-03-28T02:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-03-28T06:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-03-29T05:00:00Z')),
    },
  },
  {
    id: 'bahrain_2026',
    seasonId: '2026',
    round: 4,
    name: 'Bahrain Grand Prix',
    officialName: 'Formula 1 Gulf Air Bahrain Grand Prix 2026',
    circuitId: 'bahrain',
    circuitName: 'Bahrain International Circuit',
    country: 'Bahrain',
    city: 'Sakhir',
    timezone: 'Asia/Bahrain',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-04-10T11:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-04-10T15:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-04-11T12:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-04-11T16:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-04-12T15:00:00Z')),
    },
  },
  {
    id: 'saudi_2026',
    seasonId: '2026',
    round: 5,
    name: 'Saudi Arabian Grand Prix',
    officialName: 'Formula 1 STC Saudi Arabian Grand Prix 2026',
    circuitId: 'jeddah',
    circuitName: 'Jeddah Corniche Circuit',
    country: 'Saudi Arabia',
    city: 'Jeddah',
    timezone: 'Asia/Riyadh',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-04-17T13:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-04-17T17:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-04-18T13:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-04-18T17:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-04-19T17:00:00Z')),
    },
  },
  {
    id: 'miami_2026',
    seasonId: '2026',
    round: 6,
    name: 'Miami Grand Prix',
    officialName: 'Formula 1 Crypto.com Miami Grand Prix 2026',
    circuitId: 'miami',
    circuitName: 'Miami International Autodrome',
    country: 'United States',
    city: 'Miami',
    timezone: 'America/New_York',
    hasSprint: true,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-05-01T18:30:00Z')),
      sprintQualifying: admin.firestore.Timestamp.fromDate(new Date('2026-05-01T22:30:00Z')),
      sprint: admin.firestore.Timestamp.fromDate(new Date('2026-05-02T16:00:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-05-02T20:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-05-03T20:00:00Z')),
    },
  },
  {
    id: 'canada_2026',
    seasonId: '2026',
    round: 7,
    name: 'Canadian Grand Prix',
    officialName: 'Formula 1 AWS Grand Prix du Canada 2026',
    circuitId: 'montreal',
    circuitName: 'Circuit Gilles Villeneuve',
    country: 'Canada',
    city: 'Montreal',
    timezone: 'America/Toronto',
    hasSprint: true,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-05-22T17:30:00Z')),
      sprintQualifying: admin.firestore.Timestamp.fromDate(new Date('2026-05-22T21:30:00Z')),
      sprint: admin.firestore.Timestamp.fromDate(new Date('2026-05-23T16:00:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-05-23T20:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-05-24T18:00:00Z')),
    },
  },
  {
    id: 'monaco_2026',
    seasonId: '2026',
    round: 8,
    name: 'Monaco Grand Prix',
    officialName: 'Formula 1 Grand Prix de Monaco 2026',
    circuitId: 'monaco',
    circuitName: 'Circuit de Monaco',
    country: 'Monaco',
    city: 'Monte Carlo',
    timezone: 'Europe/Monaco',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-06-05T11:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-06-05T15:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-06-06T10:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-06-06T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-06-07T13:00:00Z')),
    },
  },
  {
    id: 'spain_2026',
    seasonId: '2026',
    round: 9,
    name: 'Spanish Grand Prix',
    officialName: 'Formula 1 Aramco Gran Premio de Espana 2026',
    circuitId: 'barcelona',
    circuitName: 'Circuit de Barcelona-Catalunya',
    country: 'Spain',
    city: 'Barcelona',
    timezone: 'Europe/Madrid',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-06-12T11:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-06-12T15:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-06-13T10:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-06-13T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-06-14T13:00:00Z')),
    },
  },
  {
    id: 'austria_2026',
    seasonId: '2026',
    round: 10,
    name: 'Austrian Grand Prix',
    officialName: 'Formula 1 Rolex Grosser Preis von Osterreich 2026',
    circuitId: 'red_bull_ring',
    circuitName: 'Red Bull Ring',
    country: 'Austria',
    city: 'Spielberg',
    timezone: 'Europe/Vienna',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-06-26T11:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-06-26T15:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-06-27T10:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-06-27T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-06-28T13:00:00Z')),
    },
  },
  {
    id: 'britain_2026',
    seasonId: '2026',
    round: 11,
    name: 'British Grand Prix',
    officialName: 'Formula 1 Qatar Airways British Grand Prix 2026',
    circuitId: 'silverstone',
    circuitName: 'Silverstone Circuit',
    country: 'United Kingdom',
    city: 'Silverstone',
    timezone: 'Europe/London',
    hasSprint: true,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-07-03T11:30:00Z')),
      sprintQualifying: admin.firestore.Timestamp.fromDate(new Date('2026-07-03T15:30:00Z')),
      sprint: admin.firestore.Timestamp.fromDate(new Date('2026-07-04T11:00:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-07-04T15:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-07-05T14:00:00Z')),
    },
  },
  {
    id: 'belgium_2026',
    seasonId: '2026',
    round: 12,
    name: 'Belgian Grand Prix',
    officialName: 'Formula 1 Rolex Belgian Grand Prix 2026',
    circuitId: 'spa',
    circuitName: 'Circuit de Spa-Francorchamps',
    country: 'Belgium',
    city: 'Spa',
    timezone: 'Europe/Brussels',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-07-17T11:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-07-17T15:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-07-18T10:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-07-18T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-07-19T13:00:00Z')),
    },
  },
  {
    id: 'hungary_2026',
    seasonId: '2026',
    round: 13,
    name: 'Hungarian Grand Prix',
    officialName: 'Formula 1 Lenovo Hungarian Grand Prix 2026',
    circuitId: 'hungaroring',
    circuitName: 'Hungaroring',
    country: 'Hungary',
    city: 'Budapest',
    timezone: 'Europe/Budapest',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-07-24T11:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-07-24T15:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-07-25T10:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-07-25T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-07-26T13:00:00Z')),
    },
  },
  {
    id: 'netherlands_2026',
    seasonId: '2026',
    round: 14,
    name: 'Dutch Grand Prix',
    officialName: 'Formula 1 Heineken Dutch Grand Prix 2026',
    circuitId: 'zandvoort',
    circuitName: 'Circuit Zandvoort',
    country: 'Netherlands',
    city: 'Zandvoort',
    timezone: 'Europe/Amsterdam',
    hasSprint: true,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-08-21T10:30:00Z')),
      sprintQualifying: admin.firestore.Timestamp.fromDate(new Date('2026-08-21T14:30:00Z')),
      sprint: admin.firestore.Timestamp.fromDate(new Date('2026-08-22T11:00:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-08-22T15:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-08-23T13:00:00Z')),
    },
  },
  {
    id: 'italy_2026',
    seasonId: '2026',
    round: 15,
    name: 'Italian Grand Prix',
    officialName: 'Formula 1 Pirelli Gran Premio dItalia 2026',
    circuitId: 'monza',
    circuitName: 'Autodromo Nazionale Monza',
    country: 'Italy',
    city: 'Monza',
    timezone: 'Europe/Rome',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-09-04T11:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-09-04T15:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-09-05T10:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-09-05T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-09-06T13:00:00Z')),
    },
  },
  {
    id: 'madrid_2026',
    seasonId: '2026',
    round: 16,
    name: 'Spanish Grand Prix',
    officialName: 'Formula 1 Gran Premio de Madrid 2026',
    circuitId: 'madrid',
    circuitName: 'Circuito de Madrid',
    country: 'Spain',
    city: 'Madrid',
    timezone: 'Europe/Madrid',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-09-11T11:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-09-11T15:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-09-12T10:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-09-12T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-09-13T13:00:00Z')),
    },
  },
  {
    id: 'azerbaijan_2026',
    seasonId: '2026',
    round: 17,
    name: 'Azerbaijan Grand Prix',
    officialName: 'Formula 1 Qatar Airways Azerbaijan Grand Prix 2026',
    circuitId: 'baku',
    circuitName: 'Baku City Circuit',
    country: 'Azerbaijan',
    city: 'Baku',
    timezone: 'Asia/Baku',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-09-24T09:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-09-24T13:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-09-25T08:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-09-25T12:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-09-26T11:00:00Z')),
    },
  },
  {
    id: 'singapore_2026',
    seasonId: '2026',
    round: 18,
    name: 'Singapore Grand Prix',
    officialName: 'Formula 1 Singapore Airlines Singapore Grand Prix 2026',
    circuitId: 'marina_bay',
    circuitName: 'Marina Bay Street Circuit',
    country: 'Singapore',
    city: 'Singapore',
    timezone: 'Asia/Singapore',
    hasSprint: true,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-10-09T09:30:00Z')),
      sprintQualifying: admin.firestore.Timestamp.fromDate(new Date('2026-10-09T13:30:00Z')),
      sprint: admin.firestore.Timestamp.fromDate(new Date('2026-10-10T10:00:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-10-10T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-10-11T12:00:00Z')),
    },
  },
  {
    id: 'usa_2026',
    seasonId: '2026',
    round: 19,
    name: 'United States Grand Prix',
    officialName: 'Formula 1 Pirelli United States Grand Prix 2026',
    circuitId: 'cota',
    circuitName: 'Circuit of the Americas',
    country: 'United States',
    city: 'Austin',
    timezone: 'America/Chicago',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-10-23T17:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-10-23T21:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-10-24T18:00:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-10-24T22:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-10-25T19:00:00Z')),
    },
  },
  {
    id: 'mexico_2026',
    seasonId: '2026',
    round: 20,
    name: 'Mexico City Grand Prix',
    officialName: 'Formula 1 Gran Premio de la Ciudad de Mexico 2026',
    circuitId: 'hermanos_rodriguez',
    circuitName: 'Autodromo Hermanos Rodriguez',
    country: 'Mexico',
    city: 'Mexico City',
    timezone: 'America/Mexico_City',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-10-30T18:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-10-30T22:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-10-31T17:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-10-31T21:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-11-01T20:00:00Z')),
    },
  },
  {
    id: 'brazil_2026',
    seasonId: '2026',
    round: 21,
    name: 'Sao Paulo Grand Prix',
    officialName: 'Formula 1 Lenovo Grande Premio de Sao Paulo 2026',
    circuitId: 'interlagos',
    circuitName: 'Autodromo Jose Carlos Pace',
    country: 'Brazil',
    city: 'Sao Paulo',
    timezone: 'America/Sao_Paulo',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-11-06T14:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-11-06T18:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-11-07T14:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-11-07T18:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-11-08T17:00:00Z')),
    },
  },
  {
    id: 'las_vegas_2026',
    seasonId: '2026',
    round: 22,
    name: 'Las Vegas Grand Prix',
    officialName: 'Formula 1 Heineken Silver Las Vegas Grand Prix 2026',
    circuitId: 'las_vegas',
    circuitName: 'Las Vegas Strip Circuit',
    country: 'United States',
    city: 'Las Vegas',
    timezone: 'America/Los_Angeles',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-11-20T02:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-11-20T06:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-11-21T02:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-11-21T06:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-11-22T06:00:00Z')),
    },
  },
  {
    id: 'qatar_2026',
    seasonId: '2026',
    round: 23,
    name: 'Qatar Grand Prix',
    officialName: 'Formula 1 Qatar Airways Qatar Grand Prix 2026',
    circuitId: 'lusail',
    circuitName: 'Lusail International Circuit',
    country: 'Qatar',
    city: 'Lusail',
    timezone: 'Asia/Qatar',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-11-27T13:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-11-27T17:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-11-28T14:00:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-11-28T18:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-11-29T17:00:00Z')),
    },
  },
  {
    id: 'abu_dhabi_2026',
    seasonId: '2026',
    round: 24,
    name: 'Abu Dhabi Grand Prix',
    officialName: 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2026',
    circuitId: 'yas_marina',
    circuitName: 'Yas Marina Circuit',
    country: 'United Arab Emirates',
    city: 'Abu Dhabi',
    timezone: 'Asia/Dubai',
    hasSprint: false,
    status: 'upcoming',
    schedule: {
      fp1: admin.firestore.Timestamp.fromDate(new Date('2026-12-04T09:30:00Z')),
      fp2: admin.firestore.Timestamp.fromDate(new Date('2026-12-04T13:00:00Z')),
      fp3: admin.firestore.Timestamp.fromDate(new Date('2026-12-05T10:30:00Z')),
      qualifying: admin.firestore.Timestamp.fromDate(new Date('2026-12-05T14:00:00Z')),
      race: admin.firestore.Timestamp.fromDate(new Date('2026-12-06T13:00:00Z')),
    },
  },
];

// ============================================
// Season Configuration
// ============================================
const season = {
  id: '2026',
  year: 2026,
  name: 'F1 2026 Season',
  isActive: true,
  startDate: admin.firestore.Timestamp.fromDate(new Date('2026-03-06')),
  endDate: admin.firestore.Timestamp.fromDate(new Date('2026-12-06')),
  totalRaces: 24,
  currentRound: 1,
  budget: 1000,
  teamSize: 5,
};

// ============================================
// Main Seeding Function
// ============================================
async function seedDatabase() {
  console.log('\n🏎️  F1 Fantasy Database Seeder\n');
  console.log('=' .repeat(50));

  try {
    // Seed Drivers
    console.log('\n📋 Seeding drivers collection...');
    const driversRef = db.collection('drivers');
    for (const driver of drivers) {
      await driversRef.doc(driver.id).set(driver);
      console.log(`   ✓ ${driver.name} (${driver.shortName})`);
    }
    console.log(`   → ${drivers.length} drivers added`);

    // Seed Constructors
    console.log('\n🏭 Seeding constructors collection...');
    const constructorsRef = db.collection('constructors');
    for (const constructor of constructors) {
      await constructorsRef.doc(constructor.id).set(constructor);
      console.log(`   ✓ ${constructor.name}`);
    }
    console.log(`   → ${constructors.length} constructors added`);

    // Seed Races
    console.log('\n🏁 Seeding races collection...');
    const racesRef = db.collection('races');
    for (const race of races) {
      await racesRef.doc(race.id).set(race);
      console.log(`   ✓ Round ${race.round}: ${race.name}`);
    }
    console.log(`   → ${races.length} races added`);

    // Seed Season
    console.log('\n📅 Seeding seasons collection...');
    const seasonsRef = db.collection('seasons');
    await seasonsRef.doc(season.id).set(season);
    console.log(`   ✓ ${season.name}`);

    console.log('\n' + '=' .repeat(50));
    console.log('✅ Database seeding complete!\n');
    console.log('Collections created:');
    console.log('   • drivers (20 documents)');
    console.log('   • constructors (10 documents)');
    console.log('   • races (24 documents)');
    console.log('   • seasons (1 document)');
    console.log('\nYou can now switch from demo mode to Firebase mode.\n');

  } catch (error) {
    console.error('\n❌ Error seeding database:', error);
    process.exit(1);
  }

  process.exit(0);
}

// Run the seeder
seedDatabase();
