/**
 * Seed data script for F1 Fantasy App
 * 2026 Season Data with pricing based on 2025 standings
 *
 * Usage: npx ts-node scripts/seedData.ts
 *
 * PRICING FORMULA (from docs/pricing-rules.txt):
 * - price = (previousSeasonPoints / 24 races) * $10 per point
 * - A-tier: price > $200
 * - B-tier: price <= $200
 */

// Pricing configuration (mirrors src/config/pricing.config.ts)
const PRICING = {
  RACES_PER_SEASON: 24,
  DOLLARS_PER_POINT: 10,
  A_TIER_THRESHOLD: 200,
  MIN_PRICE: 5,
  MAX_PRICE: 500,
};

// Calculate price from previous season points
function calcPrice(prevSeasonPoints: number): number {
  const avgPPR = prevSeasonPoints / PRICING.RACES_PER_SEASON;
  const price = Math.round(avgPPR * PRICING.DOLLARS_PER_POINT);
  return Math.max(PRICING.MIN_PRICE, Math.min(PRICING.MAX_PRICE, price));
}

// Get tier based on price
function getTier(price: number): 'A' | 'B' {
  return price > PRICING.A_TIER_THRESHOLD ? 'A' : 'B';
}

// 2025 Season Points (estimated/projected for 2025 season)
const SEASON_2025_POINTS = {
  norris: 510,      // Championship contender
  verstappen: 500,  // Championship contender
  piastri: 380,     // Strong season
  leclerc: 340,     // Consistent podiums
  russell: 290,     // Regular points
  hamilton: 260,    // Adapting to Ferrari
  sainz: 240,       // Strong in Williams
  alonso: 150,      // Veteran experience
  antonelli: 120,   // Rookie season
  albon: 100,       // Solid midfield
  stroll: 80,       // Occasional points
  hulkenberg: 70,   // Points finisher
  gasly: 65,        // Alpine struggles
  ocon: 60,         // Haas move
  hadjar: 40,       // Rookie at RB
  bearman: 35,      // Rookie at Haas
  lawson: 30,       // Alpine rookie
  bortoleto: 25,    // Sauber rookie
  doohan: 20,       // Alpine
  colapinto: 15,    // Sauber
  bottas: 10,       // Cadillac new team
  perez: 10,        // Cadillac new team
  lindblad: 0,      // Reserve
};

export const drivers2026 = [
  // A-Tier Drivers (price > $200)
  {
    id: 'norris',
    name: 'Lando Norris',
    shortName: 'NOR',
    number: 1,
    constructorId: 'mclaren',
    constructorName: 'McLaren F1 Team',
    nationality: 'British',
    previousSeasonPoints: SEASON_2025_POINTS.norris,
    price: calcPrice(SEASON_2025_POINTS.norris),         // $213
    previousPrice: calcPrice(SEASON_2025_POINTS.norris),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.norris)),
    isActive: true,
  },
  {
    id: 'verstappen',
    name: 'Max Verstappen',
    shortName: 'VER',
    number: 1,
    constructorId: 'red_bull',
    constructorName: 'Oracle Red Bull Racing',
    nationality: 'Dutch',
    previousSeasonPoints: SEASON_2025_POINTS.verstappen,
    price: calcPrice(SEASON_2025_POINTS.verstappen),     // $208
    previousPrice: calcPrice(SEASON_2025_POINTS.verstappen),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.verstappen)),
    isActive: true,
  },
  {
    id: 'piastri',
    name: 'Oscar Piastri',
    shortName: 'PIA',
    number: 81,
    constructorId: 'mclaren',
    constructorName: 'McLaren F1 Team',
    nationality: 'Australian',
    previousSeasonPoints: SEASON_2025_POINTS.piastri,
    price: calcPrice(SEASON_2025_POINTS.piastri),        // $158
    previousPrice: calcPrice(SEASON_2025_POINTS.piastri),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.piastri)),
    isActive: true,
  },
  {
    id: 'leclerc',
    name: 'Charles Leclerc',
    shortName: 'LEC',
    number: 16,
    constructorId: 'ferrari',
    constructorName: 'Scuderia Ferrari',
    nationality: 'Monegasque',
    previousSeasonPoints: SEASON_2025_POINTS.leclerc,
    price: calcPrice(SEASON_2025_POINTS.leclerc),        // $142
    previousPrice: calcPrice(SEASON_2025_POINTS.leclerc),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.leclerc)),
    isActive: true,
  },
  {
    id: 'russell',
    name: 'George Russell',
    shortName: 'RUS',
    number: 63,
    constructorId: 'mercedes',
    constructorName: 'Mercedes-AMG Petronas F1 Team',
    nationality: 'British',
    previousSeasonPoints: SEASON_2025_POINTS.russell,
    price: calcPrice(SEASON_2025_POINTS.russell),        // $121
    previousPrice: calcPrice(SEASON_2025_POINTS.russell),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.russell)),
    isActive: true,
  },
  // B-Tier Drivers (price <= $200)
  {
    id: 'hamilton',
    name: 'Lewis Hamilton',
    shortName: 'HAM',
    number: 44,
    constructorId: 'ferrari',
    constructorName: 'Scuderia Ferrari',
    nationality: 'British',
    previousSeasonPoints: SEASON_2025_POINTS.hamilton,
    price: calcPrice(SEASON_2025_POINTS.hamilton),       // $108
    previousPrice: calcPrice(SEASON_2025_POINTS.hamilton),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.hamilton)),
    isActive: true,
  },
  {
    id: 'sainz',
    name: 'Carlos Sainz Jr.',
    shortName: 'SAI',
    number: 55,
    constructorId: 'williams',
    constructorName: 'Williams Racing',
    nationality: 'Spanish',
    previousSeasonPoints: SEASON_2025_POINTS.sainz,
    price: calcPrice(SEASON_2025_POINTS.sainz),          // $100
    previousPrice: calcPrice(SEASON_2025_POINTS.sainz),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.sainz)),
    isActive: true,
  },
  {
    id: 'alonso',
    name: 'Fernando Alonso',
    shortName: 'ALO',
    number: 14,
    constructorId: 'aston_martin',
    constructorName: 'Aston Martin Aramco F1 Team',
    nationality: 'Spanish',
    previousSeasonPoints: SEASON_2025_POINTS.alonso,
    price: calcPrice(SEASON_2025_POINTS.alonso),         // $63
    previousPrice: calcPrice(SEASON_2025_POINTS.alonso),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.alonso)),
    isActive: true,
  },
  {
    id: 'antonelli',
    name: 'Kimi Antonelli',
    shortName: 'ANT',
    number: 12,
    constructorId: 'mercedes',
    constructorName: 'Mercedes-AMG Petronas F1 Team',
    nationality: 'Italian',
    previousSeasonPoints: SEASON_2025_POINTS.antonelli,
    price: calcPrice(SEASON_2025_POINTS.antonelli),      // $50
    previousPrice: calcPrice(SEASON_2025_POINTS.antonelli),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.antonelli)),
    isActive: true,
  },
  {
    id: 'albon',
    name: 'Alexander Albon',
    shortName: 'ALB',
    number: 23,
    constructorId: 'williams',
    constructorName: 'Williams Racing',
    nationality: 'Thai-British',
    previousSeasonPoints: SEASON_2025_POINTS.albon,
    price: calcPrice(SEASON_2025_POINTS.albon),          // $42
    previousPrice: calcPrice(SEASON_2025_POINTS.albon),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.albon)),
    isActive: true,
  },
  {
    id: 'stroll',
    name: 'Lance Stroll',
    shortName: 'STR',
    number: 18,
    constructorId: 'aston_martin',
    constructorName: 'Aston Martin Aramco F1 Team',
    nationality: 'Canadian',
    previousSeasonPoints: SEASON_2025_POINTS.stroll,
    price: calcPrice(SEASON_2025_POINTS.stroll),         // $33
    previousPrice: calcPrice(SEASON_2025_POINTS.stroll),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.stroll)),
    isActive: true,
  },
  {
    id: 'hulkenberg',
    name: 'Nico Hulkenberg',
    shortName: 'HUL',
    number: 27,
    constructorId: 'sauber',
    constructorName: 'Stake F1 Team Kick Sauber',
    nationality: 'German',
    previousSeasonPoints: SEASON_2025_POINTS.hulkenberg,
    price: calcPrice(SEASON_2025_POINTS.hulkenberg),     // $29
    previousPrice: calcPrice(SEASON_2025_POINTS.hulkenberg),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.hulkenberg)),
    isActive: true,
  },
  {
    id: 'gasly',
    name: 'Pierre Gasly',
    shortName: 'GAS',
    number: 10,
    constructorId: 'alpine',
    constructorName: 'BWT Alpine F1 Team',
    nationality: 'French',
    previousSeasonPoints: SEASON_2025_POINTS.gasly,
    price: calcPrice(SEASON_2025_POINTS.gasly),          // $27
    previousPrice: calcPrice(SEASON_2025_POINTS.gasly),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.gasly)),
    isActive: true,
  },
  {
    id: 'ocon',
    name: 'Esteban Ocon',
    shortName: 'OCO',
    number: 31,
    constructorId: 'haas',
    constructorName: 'MoneyGram Haas F1 Team',
    nationality: 'French',
    previousSeasonPoints: SEASON_2025_POINTS.ocon,
    price: calcPrice(SEASON_2025_POINTS.ocon),           // $25
    previousPrice: calcPrice(SEASON_2025_POINTS.ocon),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.ocon)),
    isActive: true,
  },
  {
    id: 'hadjar',
    name: 'Isack Hadjar',
    shortName: 'HAD',
    number: 6,
    constructorId: 'red_bull',
    constructorName: 'Oracle Red Bull Racing',
    nationality: 'French',
    previousSeasonPoints: SEASON_2025_POINTS.hadjar,
    price: calcPrice(SEASON_2025_POINTS.hadjar),         // $17
    previousPrice: calcPrice(SEASON_2025_POINTS.hadjar),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.hadjar)),
    isActive: true,
  },
  {
    id: 'bearman',
    name: 'Oliver Bearman',
    shortName: 'BEA',
    number: 87,
    constructorId: 'haas',
    constructorName: 'MoneyGram Haas F1 Team',
    nationality: 'British',
    previousSeasonPoints: SEASON_2025_POINTS.bearman,
    price: calcPrice(SEASON_2025_POINTS.bearman),        // $15
    previousPrice: calcPrice(SEASON_2025_POINTS.bearman),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.bearman)),
    isActive: true,
  },
  {
    id: 'lawson',
    name: 'Liam Lawson',
    shortName: 'LAW',
    number: 30,
    constructorId: 'rb',
    constructorName: 'Visa Cash App RB F1 Team',
    nationality: 'New Zealander',
    previousSeasonPoints: SEASON_2025_POINTS.lawson,
    price: calcPrice(SEASON_2025_POINTS.lawson),         // $13
    previousPrice: calcPrice(SEASON_2025_POINTS.lawson),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.lawson)),
    isActive: true,
  },
  {
    id: 'bortoleto',
    name: 'Gabriel Bortoleto',
    shortName: 'BOR',
    number: 5,
    constructorId: 'sauber',
    constructorName: 'Stake F1 Team Kick Sauber',
    nationality: 'Brazilian',
    previousSeasonPoints: SEASON_2025_POINTS.bortoleto,
    price: calcPrice(SEASON_2025_POINTS.bortoleto),      // $10
    previousPrice: calcPrice(SEASON_2025_POINTS.bortoleto),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.bortoleto)),
    isActive: true,
  },
  {
    id: 'doohan',
    name: 'Jack Doohan',
    shortName: 'DOO',
    number: 7,
    constructorId: 'alpine',
    constructorName: 'BWT Alpine F1 Team',
    nationality: 'Australian',
    previousSeasonPoints: SEASON_2025_POINTS.doohan,
    price: calcPrice(SEASON_2025_POINTS.doohan),         // $8
    previousPrice: calcPrice(SEASON_2025_POINTS.doohan),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.doohan)),
    isActive: true,
  },
  {
    id: 'colapinto',
    name: 'Franco Colapinto',
    shortName: 'COL',
    number: 43,
    constructorId: 'sauber',
    constructorName: 'Stake F1 Team Kick Sauber',
    nationality: 'Argentinian',
    previousSeasonPoints: SEASON_2025_POINTS.colapinto,
    price: calcPrice(SEASON_2025_POINTS.colapinto),      // $6
    previousPrice: calcPrice(SEASON_2025_POINTS.colapinto),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.colapinto)),
    isActive: true,
  },
  {
    id: 'bottas',
    name: 'Valtteri Bottas',
    shortName: 'BOT',
    number: 77,
    constructorId: 'cadillac',
    constructorName: 'Cadillac F1',
    nationality: 'Finnish',
    previousSeasonPoints: SEASON_2025_POINTS.bottas,
    price: calcPrice(SEASON_2025_POINTS.bottas),         // $5 (min)
    previousPrice: calcPrice(SEASON_2025_POINTS.bottas),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.bottas)),
    isActive: true,
  },
  {
    id: 'perez',
    name: 'Sergio Perez',
    shortName: 'PER',
    number: 11,
    constructorId: 'cadillac',
    constructorName: 'Cadillac F1',
    nationality: 'Mexican',
    previousSeasonPoints: SEASON_2025_POINTS.perez,
    price: calcPrice(SEASON_2025_POINTS.perez),          // $5 (min)
    previousPrice: calcPrice(SEASON_2025_POINTS.perez),
    seasonPoints: 0,
    fantasyPoints: 0,
    tier: getTier(calcPrice(SEASON_2025_POINTS.perez)),
    isActive: true,
  },
];

export const constructors2026 = [
  {
    id: 'mclaren',
    name: 'McLaren F1 Team',
    shortName: 'MCL',
    nationality: 'British',
    primaryColor: '#FF8000',
    secondaryColor: '#47C7FC',
    price: 400,
    previousPrice: 380,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['norris', 'piastri'],
    isActive: true,
  },
  {
    id: 'mercedes',
    name: 'Mercedes-AMG Petronas F1 Team',
    shortName: 'MER',
    nationality: 'German',
    primaryColor: '#27F4D2',
    secondaryColor: '#000000',
    price: 258,
    previousPrice: 250,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['russell', 'antonelli'],
    isActive: true,
  },
  {
    id: 'red_bull',
    name: 'Oracle Red Bull Racing',
    shortName: 'RBR',
    nationality: 'Austrian',
    primaryColor: '#3671C6',
    secondaryColor: '#FFD700',
    price: 251,
    previousPrice: 245,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['verstappen', 'hadjar'],
    isActive: true,
  },
  {
    id: 'ferrari',
    name: 'Scuderia Ferrari',
    shortName: 'FER',
    nationality: 'Italian',
    primaryColor: '#E80020',
    secondaryColor: '#FFEB00',
    price: 230,
    previousPrice: 225,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['leclerc', 'hamilton'],
    isActive: true,
  },
  {
    id: 'williams',
    name: 'Williams Racing',
    shortName: 'WIL',
    nationality: 'British',
    primaryColor: '#64C4FF',
    secondaryColor: '#00A3E0',
    price: 128,
    previousPrice: 125,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['sainz', 'albon'],
    isActive: true,
  },
  {
    id: 'racing_bulls',
    name: 'Racing Bulls',
    shortName: 'RB',
    nationality: 'Italian',
    primaryColor: '#6692FF',
    secondaryColor: '#1E5BC6',
    price: 111,
    previousPrice: 108,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['lawson', 'lindblad'],
    isActive: true,
  },
  {
    id: 'aston_martin',
    name: 'Aston Martin Aramco F1 Team',
    shortName: 'AMR',
    nationality: 'British',
    primaryColor: '#229971',
    secondaryColor: '#CEDC00',
    price: 110,
    previousPrice: 107,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['alonso', 'stroll'],
    isActive: true,
  },
  {
    id: 'haas',
    name: 'MoneyGram Haas F1 Team',
    shortName: 'HAA',
    nationality: 'American',
    primaryColor: '#B6BABD',
    secondaryColor: '#E10600',
    price: 106,
    previousPrice: 103,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['ocon', 'bearman'],
    isActive: true,
  },
  {
    id: 'sauber',
    name: 'Stake F1 Team Kick Sauber',
    shortName: 'SAU',
    nationality: 'Swiss',
    primaryColor: '#52E252',
    secondaryColor: '#000000',
    price: 102,
    previousPrice: 100,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['hulkenberg', 'bortoleto'],
    isActive: true,
  },
  {
    id: 'alpine',
    name: 'BWT Alpine F1 Team',
    shortName: 'ALP',
    nationality: 'French',
    primaryColor: '#FF87BC',
    secondaryColor: '#0093CC',
    price: 84,
    previousPrice: 82,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['gasly', 'colapinto'],
    isActive: true,
  },
  {
    id: 'cadillac',
    name: 'Cadillac F1',
    shortName: 'CAD',
    nationality: 'American',
    primaryColor: '#524E4E',
    secondaryColor: '#000000',
    price: 75,
    previousPrice: 75,
    seasonPoints: 0,
    fantasyPoints: 0,
    drivers: ['bottas', 'perez'],
    isActive: true,
  },
];

// Race results for completed races
export const raceResults2025 = {
  australia_2025: {
    race: [
      { driverId: 'norris', position: 1, points: 25 },
      { driverId: 'verstappen', position: 2, points: 18 },
      { driverId: 'russell', position: 3, points: 15 },
      { driverId: 'piastri', position: 4, points: 12 },
      { driverId: 'leclerc', position: 5, points: 10 },
      { driverId: 'hamilton', position: 6, points: 8 },
      { driverId: 'sainz', position: 7, points: 6 },
      { driverId: 'perez', position: 8, points: 4 },
      { driverId: 'alonso', position: 9, points: 2 },
      { driverId: 'stroll', position: 10, points: 1 },
    ],
  },
  china_2025: {
    race: [
      { driverId: 'piastri', position: 1, points: 25 },
      { driverId: 'norris', position: 2, points: 18 },
      { driverId: 'russell', position: 3, points: 15 },
      { driverId: 'verstappen', position: 4, points: 12 },
      { driverId: 'leclerc', position: 5, points: 10 },
      { driverId: 'hamilton', position: 6, points: 8 },
      { driverId: 'sainz', position: 7, points: 6 },
      { driverId: 'perez', position: 8, points: 4 },
      { driverId: 'alonso', position: 9, points: 2 },
      { driverId: 'stroll', position: 10, points: 1 },
    ],
  },
  japan_2025: {
    race: [
      { driverId: 'verstappen', position: 1, points: 25 },
      { driverId: 'norris', position: 2, points: 18 },
      { driverId: 'piastri', position: 3, points: 15 },
      { driverId: 'leclerc', position: 4, points: 12 },
      { driverId: 'russell', position: 5, points: 10 },
      { driverId: 'hamilton', position: 6, points: 8 },
      { driverId: 'sainz', position: 7, points: 6 },
      { driverId: 'perez', position: 8, points: 4 },
      { driverId: 'alonso', position: 9, points: 2 },
      { driverId: 'hadjar', position: 10, points: 1 },
    ],
  },
};

export const races2025 = [
  {
    id: 'australia_2025',
    seasonId: '2025',
    round: 1,
    name: 'Australian Grand Prix',
    officialName: 'Formula 1 Rolex Australian Grand Prix 2025',
    circuitId: 'albert_park',
    circuitName: 'Albert Park Circuit',
    country: 'Australia',
    city: 'Melbourne',
    timezone: 'Australia/Melbourne',
    hasSprint: false,
    status: 'completed' as const,
    schedule: {
      fp1: new Date('2025-03-14T01:30:00Z'),
      fp2: new Date('2025-03-14T05:00:00Z'),
      fp3: new Date('2025-03-15T01:30:00Z'),
      qualifying: new Date('2025-03-15T05:00:00Z'),
      race: new Date('2025-03-16T04:00:00Z'),
    },
    results: raceResults2025.australia_2025,
  },
  {
    id: 'china_2025',
    seasonId: '2025',
    round: 2,
    name: 'Chinese Grand Prix',
    officialName: 'Formula 1 Lenovo Chinese Grand Prix 2025',
    circuitId: 'shanghai',
    circuitName: 'Shanghai International Circuit',
    country: 'China',
    city: 'Shanghai',
    timezone: 'Asia/Shanghai',
    hasSprint: true,
    status: 'completed' as const,
    schedule: {
      fp1: new Date('2025-03-21T03:30:00Z'),
      sprintQualifying: new Date('2025-03-21T07:30:00Z'),
      sprint: new Date('2025-03-22T03:00:00Z'),
      qualifying: new Date('2025-03-22T07:00:00Z'),
      race: new Date('2025-03-23T07:00:00Z'),
    },
    results: raceResults2025.china_2025,
  },
  {
    id: 'japan_2025',
    seasonId: '2025',
    round: 3,
    name: 'Japanese Grand Prix',
    officialName: 'Formula 1 Lenovo Japanese Grand Prix 2025',
    circuitId: 'suzuka',
    circuitName: 'Suzuka International Racing Course',
    country: 'Japan',
    city: 'Suzuka',
    timezone: 'Asia/Tokyo',
    hasSprint: false,
    status: 'completed' as const,
    schedule: {
      fp1: new Date('2025-04-04T02:30:00Z'),
      fp2: new Date('2025-04-04T06:00:00Z'),
      fp3: new Date('2025-04-05T02:30:00Z'),
      qualifying: new Date('2025-04-05T06:00:00Z'),
      race: new Date('2025-04-06T05:00:00Z'),
    },
    results: raceResults2025.japan_2025,
  },
  {
    id: 'bahrain_2025',
    seasonId: '2025',
    round: 4,
    name: 'Bahrain Grand Prix',
    officialName: 'Formula 1 Gulf Air Bahrain Grand Prix 2025',
    circuitId: 'bahrain',
    circuitName: 'Bahrain International Circuit',
    country: 'Bahrain',
    city: 'Sakhir',
    timezone: 'Asia/Bahrain',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-04-11T11:30:00Z'),
      fp2: new Date('2025-04-11T15:00:00Z'),
      fp3: new Date('2025-04-12T12:30:00Z'),
      qualifying: new Date('2025-04-12T16:00:00Z'),
      race: new Date('2025-04-13T15:00:00Z'),
    },
  },
  {
    id: 'saudi_2025',
    seasonId: '2025',
    round: 5,
    name: 'Saudi Arabian Grand Prix',
    officialName: 'Formula 1 STC Saudi Arabian Grand Prix 2025',
    circuitId: 'jeddah',
    circuitName: 'Jeddah Corniche Circuit',
    country: 'Saudi Arabia',
    city: 'Jeddah',
    timezone: 'Asia/Riyadh',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-04-18T13:30:00Z'),
      fp2: new Date('2025-04-18T17:00:00Z'),
      fp3: new Date('2025-04-19T13:30:00Z'),
      qualifying: new Date('2025-04-19T17:00:00Z'),
      race: new Date('2025-04-20T17:00:00Z'),
    },
  },
  {
    id: 'miami_2025',
    seasonId: '2025',
    round: 6,
    name: 'Miami Grand Prix',
    officialName: 'Formula 1 Crypto.com Miami Grand Prix 2025',
    circuitId: 'miami',
    circuitName: 'Miami International Autodrome',
    country: 'United States',
    city: 'Miami',
    timezone: 'America/New_York',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-05-02T18:30:00Z'),
      sprintQualifying: new Date('2025-05-02T22:30:00Z'),
      sprint: new Date('2025-05-03T16:00:00Z'),
      qualifying: new Date('2025-05-03T20:00:00Z'),
      race: new Date('2025-05-04T20:00:00Z'),
    },
  },
  {
    id: 'emilia_romagna_2025',
    seasonId: '2025',
    round: 7,
    name: 'Emilia Romagna Grand Prix',
    officialName: 'Formula 1 MSC Cruises Emilia Romagna Grand Prix 2025',
    circuitId: 'imola',
    circuitName: 'Autodromo Enzo e Dino Ferrari',
    country: 'Italy',
    city: 'Imola',
    timezone: 'Europe/Rome',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-05-16T11:30:00Z'),
      fp2: new Date('2025-05-16T15:00:00Z'),
      fp3: new Date('2025-05-17T10:30:00Z'),
      qualifying: new Date('2025-05-17T14:00:00Z'),
      race: new Date('2025-05-18T13:00:00Z'),
    },
  },
  {
    id: 'monaco_2025',
    seasonId: '2025',
    round: 8,
    name: 'Monaco Grand Prix',
    officialName: 'Formula 1 Grand Prix de Monaco 2025',
    circuitId: 'monaco',
    circuitName: 'Circuit de Monaco',
    country: 'Monaco',
    city: 'Monte Carlo',
    timezone: 'Europe/Monaco',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-05-23T11:30:00Z'),
      fp2: new Date('2025-05-23T15:00:00Z'),
      fp3: new Date('2025-05-24T10:30:00Z'),
      qualifying: new Date('2025-05-24T14:00:00Z'),
      race: new Date('2025-05-25T13:00:00Z'),
    },
  },
  {
    id: 'spain_2025',
    seasonId: '2025',
    round: 9,
    name: 'Spanish Grand Prix',
    officialName: 'Formula 1 Aramco Gran Premio de Espana 2025',
    circuitId: 'barcelona',
    circuitName: 'Circuit de Barcelona-Catalunya',
    country: 'Spain',
    city: 'Barcelona',
    timezone: 'Europe/Madrid',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-05-30T11:30:00Z'),
      fp2: new Date('2025-05-30T15:00:00Z'),
      fp3: new Date('2025-05-31T10:30:00Z'),
      qualifying: new Date('2025-05-31T14:00:00Z'),
      race: new Date('2025-06-01T13:00:00Z'),
    },
  },
  {
    id: 'canada_2025',
    seasonId: '2025',
    round: 10,
    name: 'Canadian Grand Prix',
    officialName: 'Formula 1 AWS Grand Prix du Canada 2025',
    circuitId: 'montreal',
    circuitName: 'Circuit Gilles Villeneuve',
    country: 'Canada',
    city: 'Montreal',
    timezone: 'America/Toronto',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-06-13T17:30:00Z'),
      fp2: new Date('2025-06-13T21:00:00Z'),
      fp3: new Date('2025-06-14T16:30:00Z'),
      qualifying: new Date('2025-06-14T20:00:00Z'),
      race: new Date('2025-06-15T18:00:00Z'),
    },
  },
  {
    id: 'austria_2025',
    seasonId: '2025',
    round: 11,
    name: 'Austrian Grand Prix',
    officialName: 'Formula 1 Rolex Grosser Preis von Osterreich 2025',
    circuitId: 'red_bull_ring',
    circuitName: 'Red Bull Ring',
    country: 'Austria',
    city: 'Spielberg',
    timezone: 'Europe/Vienna',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-06-27T11:30:00Z'),
      fp2: new Date('2025-06-27T15:00:00Z'),
      fp3: new Date('2025-06-28T10:30:00Z'),
      qualifying: new Date('2025-06-28T14:00:00Z'),
      race: new Date('2025-06-29T13:00:00Z'),
    },
  },
  {
    id: 'britain_2025',
    seasonId: '2025',
    round: 12,
    name: 'British Grand Prix',
    officialName: 'Formula 1 Qatar Airways British Grand Prix 2025',
    circuitId: 'silverstone',
    circuitName: 'Silverstone Circuit',
    country: 'United Kingdom',
    city: 'Silverstone',
    timezone: 'Europe/London',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-07-04T11:30:00Z'),
      fp2: new Date('2025-07-04T15:00:00Z'),
      fp3: new Date('2025-07-05T10:30:00Z'),
      qualifying: new Date('2025-07-05T14:00:00Z'),
      race: new Date('2025-07-06T14:00:00Z'),
    },
  },
  {
    id: 'belgium_2025',
    seasonId: '2025',
    round: 13,
    name: 'Belgian Grand Prix',
    officialName: 'Formula 1 Rolex Belgian Grand Prix 2025',
    circuitId: 'spa',
    circuitName: 'Circuit de Spa-Francorchamps',
    country: 'Belgium',
    city: 'Spa',
    timezone: 'Europe/Brussels',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-07-25T11:30:00Z'),
      sprintQualifying: new Date('2025-07-25T15:30:00Z'),
      sprint: new Date('2025-07-26T11:00:00Z'),
      qualifying: new Date('2025-07-26T15:00:00Z'),
      race: new Date('2025-07-27T13:00:00Z'),
    },
  },
  {
    id: 'hungary_2025',
    seasonId: '2025',
    round: 14,
    name: 'Hungarian Grand Prix',
    officialName: 'Formula 1 Lenovo Hungarian Grand Prix 2025',
    circuitId: 'hungaroring',
    circuitName: 'Hungaroring',
    country: 'Hungary',
    city: 'Budapest',
    timezone: 'Europe/Budapest',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-08-01T11:30:00Z'),
      fp2: new Date('2025-08-01T15:00:00Z'),
      fp3: new Date('2025-08-02T10:30:00Z'),
      qualifying: new Date('2025-08-02T14:00:00Z'),
      race: new Date('2025-08-03T13:00:00Z'),
    },
  },
  {
    id: 'netherlands_2025',
    seasonId: '2025',
    round: 15,
    name: 'Dutch Grand Prix',
    officialName: 'Formula 1 Heineken Dutch Grand Prix 2025',
    circuitId: 'zandvoort',
    circuitName: 'Circuit Zandvoort',
    country: 'Netherlands',
    city: 'Zandvoort',
    timezone: 'Europe/Amsterdam',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-08-29T10:30:00Z'),
      fp2: new Date('2025-08-29T14:00:00Z'),
      fp3: new Date('2025-08-30T09:30:00Z'),
      qualifying: new Date('2025-08-30T13:00:00Z'),
      race: new Date('2025-08-31T13:00:00Z'),
    },
  },
  {
    id: 'italy_2025',
    seasonId: '2025',
    round: 16,
    name: 'Italian Grand Prix',
    officialName: 'Formula 1 Pirelli Gran Premio dItalia 2025',
    circuitId: 'monza',
    circuitName: 'Autodromo Nazionale Monza',
    country: 'Italy',
    city: 'Monza',
    timezone: 'Europe/Rome',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-09-05T11:30:00Z'),
      fp2: new Date('2025-09-05T15:00:00Z'),
      fp3: new Date('2025-09-06T10:30:00Z'),
      qualifying: new Date('2025-09-06T14:00:00Z'),
      race: new Date('2025-09-07T13:00:00Z'),
    },
  },
  {
    id: 'azerbaijan_2025',
    seasonId: '2025',
    round: 17,
    name: 'Azerbaijan Grand Prix',
    officialName: 'Formula 1 Qatar Airways Azerbaijan Grand Prix 2025',
    circuitId: 'baku',
    circuitName: 'Baku City Circuit',
    country: 'Azerbaijan',
    city: 'Baku',
    timezone: 'Asia/Baku',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-09-19T09:30:00Z'),
      fp2: new Date('2025-09-19T13:00:00Z'),
      fp3: new Date('2025-09-20T08:30:00Z'),
      qualifying: new Date('2025-09-20T12:00:00Z'),
      race: new Date('2025-09-21T11:00:00Z'),
    },
  },
  {
    id: 'singapore_2025',
    seasonId: '2025',
    round: 18,
    name: 'Singapore Grand Prix',
    officialName: 'Formula 1 Singapore Airlines Singapore Grand Prix 2025',
    circuitId: 'marina_bay',
    circuitName: 'Marina Bay Street Circuit',
    country: 'Singapore',
    city: 'Singapore',
    timezone: 'Asia/Singapore',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-10-03T09:30:00Z'),
      fp2: new Date('2025-10-03T13:00:00Z'),
      fp3: new Date('2025-10-04T09:30:00Z'),
      qualifying: new Date('2025-10-04T13:00:00Z'),
      race: new Date('2025-10-05T12:00:00Z'),
    },
  },
  {
    id: 'usa_2025',
    seasonId: '2025',
    round: 19,
    name: 'United States Grand Prix',
    officialName: 'Formula 1 Pirelli United States Grand Prix 2025',
    circuitId: 'cota',
    circuitName: 'Circuit of the Americas',
    country: 'United States',
    city: 'Austin',
    timezone: 'America/Chicago',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-10-17T17:30:00Z'),
      sprintQualifying: new Date('2025-10-17T21:30:00Z'),
      sprint: new Date('2025-10-18T18:00:00Z'),
      qualifying: new Date('2025-10-18T22:00:00Z'),
      race: new Date('2025-10-19T19:00:00Z'),
    },
  },
  {
    id: 'mexico_2025',
    seasonId: '2025',
    round: 20,
    name: 'Mexico City Grand Prix',
    officialName: 'Formula 1 Gran Premio de la Ciudad de Mexico 2025',
    circuitId: 'hermanos_rodriguez',
    circuitName: 'Autodromo Hermanos Rodriguez',
    country: 'Mexico',
    city: 'Mexico City',
    timezone: 'America/Mexico_City',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-10-24T18:30:00Z'),
      fp2: new Date('2025-10-24T22:00:00Z'),
      fp3: new Date('2025-10-25T17:30:00Z'),
      qualifying: new Date('2025-10-25T21:00:00Z'),
      race: new Date('2025-10-26T20:00:00Z'),
    },
  },
  {
    id: 'brazil_2025',
    seasonId: '2025',
    round: 21,
    name: 'Sao Paulo Grand Prix',
    officialName: 'Formula 1 Lenovo Grande Premio de Sao Paulo 2025',
    circuitId: 'interlagos',
    circuitName: 'Autodromo Jose Carlos Pace',
    country: 'Brazil',
    city: 'Sao Paulo',
    timezone: 'America/Sao_Paulo',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-11-07T14:30:00Z'),
      sprintQualifying: new Date('2025-11-07T18:30:00Z'),
      sprint: new Date('2025-11-08T14:00:00Z'),
      qualifying: new Date('2025-11-08T18:00:00Z'),
      race: new Date('2025-11-09T17:00:00Z'),
    },
  },
  {
    id: 'las_vegas_2025',
    seasonId: '2025',
    round: 22,
    name: 'Las Vegas Grand Prix',
    officialName: 'Formula 1 Heineken Silver Las Vegas Grand Prix 2025',
    circuitId: 'las_vegas',
    circuitName: 'Las Vegas Strip Circuit',
    country: 'United States',
    city: 'Las Vegas',
    timezone: 'America/Los_Angeles',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-11-21T02:30:00Z'),
      fp2: new Date('2025-11-21T06:00:00Z'),
      fp3: new Date('2025-11-22T02:30:00Z'),
      qualifying: new Date('2025-11-22T06:00:00Z'),
      race: new Date('2025-11-23T06:00:00Z'),
    },
  },
  {
    id: 'qatar_2025',
    seasonId: '2025',
    round: 23,
    name: 'Qatar Grand Prix',
    officialName: 'Formula 1 Qatar Airways Qatar Grand Prix 2025',
    circuitId: 'lusail',
    circuitName: 'Lusail International Circuit',
    country: 'Qatar',
    city: 'Lusail',
    timezone: 'Asia/Qatar',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-11-28T13:30:00Z'),
      sprintQualifying: new Date('2025-11-28T17:30:00Z'),
      sprint: new Date('2025-11-29T14:00:00Z'),
      qualifying: new Date('2025-11-29T18:00:00Z'),
      race: new Date('2025-11-30T17:00:00Z'),
    },
  },
  {
    id: 'abu_dhabi_2025',
    seasonId: '2025',
    round: 24,
    name: 'Abu Dhabi Grand Prix',
    officialName: 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2025',
    circuitId: 'yas_marina',
    circuitName: 'Yas Marina Circuit',
    country: 'United Arab Emirates',
    city: 'Abu Dhabi',
    timezone: 'Asia/Dubai',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-12-05T09:30:00Z'),
      fp2: new Date('2025-12-05T13:00:00Z'),
      fp3: new Date('2025-12-06T10:30:00Z'),
      qualifying: new Date('2025-12-06T14:00:00Z'),
      race: new Date('2025-12-07T13:00:00Z'),
    },
  },
];

export const season2025 = {
  id: '2025',
  year: 2025,
  name: 'F1 2025 Season',
  isActive: true,
  startDate: new Date('2025-03-14'),
  endDate: new Date('2025-12-07'),
  totalRaces: 24,
  currentRound: 4, // Next race is Bahrain (round 4)
  budget: 1000,
  teamSize: 5,
  scoringRules: {
    racePoints: [25, 18, 15, 12, 10, 8, 6, 4, 2, 1],
    sprintPoints: [8, 7, 6, 5, 4, 3, 2, 1],
    fastestLapBonus: 1,
    positionGainedBonus: 1,
    qualifyingPoints: [],
    dnfPenalty: 0,
    dsqPenalty: -5,
  },
  pricingRules: {
    greatPPMThreshold: 0.8,
    goodPPMThreshold: 0.6,
    poorPPMThreshold: 0.4,
    aTierPriceChange: { great: 15, good: 5, poor: -5, terrible: -15 },
    bTierPriceChange: { great: 10, good: 3, poor: -3, terrible: -10 },
  },
};

// 2025 Final Championship standings (used for 2026 pricing)
export const driverStandings2025 = [
  { position: 1, driverId: 'norris', points: 423 },
  { position: 2, driverId: 'verstappen', points: 421 },
  { position: 3, driverId: 'piastri', points: 410 },
  { position: 4, driverId: 'russell', points: 319 },
  { position: 5, driverId: 'leclerc', points: 242 },
  { position: 6, driverId: 'hamilton', points: 156 },
  { position: 7, driverId: 'antonelli', points: 150 },
  { position: 8, driverId: 'albon', points: 73 },
  { position: 9, driverId: 'sainz', points: 64 },
  { position: 10, driverId: 'alonso', points: 56 },
];

export const constructorStandings2025 = [
  { position: 1, constructorId: 'mclaren', points: 833 },
  { position: 2, constructorId: 'red_bull', points: 472 },
  { position: 3, constructorId: 'mercedes', points: 469 },
  { position: 4, constructorId: 'ferrari', points: 398 },
  { position: 5, constructorId: 'williams', points: 137 },
  { position: 6, constructorId: 'aston_martin', points: 89 },
  { position: 7, constructorId: 'haas', points: 79 },
  { position: 8, constructorId: 'sauber', points: 70 },
  { position: 9, constructorId: 'racing_bulls', points: 38 },
  { position: 10, constructorId: 'alpine', points: 22 },
];

console.log('2026 Season Seed Data Ready');
console.log(`Drivers: ${drivers2026.length}`);
console.log(`Constructors: ${constructors2026.length}`);
