/**
 * Seed data script for F1 Fantasy App
 * 2025 Season Data with actual race results
 *
 * Usage: npx ts-node scripts/seedData.ts
 */

// This file contains the data structures for seeding
// In a real setup, you'd run this through Firebase Admin SDK

export const drivers2025 = [
  {
    id: 'verstappen',
    name: 'Max Verstappen',
    shortName: 'VER',
    number: 1,
    constructorId: 'red_bull',
    constructorName: 'Oracle Red Bull Racing',
    nationality: 'Dutch',
    price: 320,
    previousPrice: 310,
    seasonPoints: 421,
    fantasyPoints: 421,
    tier: 'A' as const,
    isActive: true,
  },
  {
    id: 'norris',
    name: 'Lando Norris',
    shortName: 'NOR',
    number: 4,
    constructorId: 'mclaren',
    constructorName: 'McLaren F1 Team',
    nationality: 'British',
    price: 325,
    previousPrice: 290,
    seasonPoints: 423,
    fantasyPoints: 423,
    tier: 'A' as const,
    isActive: true,
  },
  {
    id: 'leclerc',
    name: 'Charles Leclerc',
    shortName: 'LEC',
    number: 16,
    constructorId: 'ferrari',
    constructorName: 'Scuderia Ferrari',
    nationality: 'Monegasque',
    price: 285,
    previousPrice: 280,
    seasonPoints: 356,
    fantasyPoints: 356,
    tier: 'A' as const,
    isActive: true,
  },
  {
    id: 'hamilton',
    name: 'Lewis Hamilton',
    shortName: 'HAM',
    number: 44,
    constructorId: 'ferrari',
    constructorName: 'Scuderia Ferrari',
    nationality: 'British',
    price: 265,
    previousPrice: 275,
    seasonPoints: 289,
    fantasyPoints: 289,
    tier: 'A' as const,
    isActive: true,
  },
  {
    id: 'piastri',
    name: 'Oscar Piastri',
    shortName: 'PIA',
    number: 81,
    constructorId: 'mclaren',
    constructorName: 'McLaren F1 Team',
    nationality: 'Australian',
    price: 290,
    previousPrice: 250,
    seasonPoints: 410,
    fantasyPoints: 410,
    tier: 'A' as const,
    isActive: true,
  },
  {
    id: 'russell',
    name: 'George Russell',
    shortName: 'RUS',
    number: 63,
    constructorId: 'mercedes',
    constructorName: 'Mercedes-AMG Petronas F1 Team',
    nationality: 'British',
    price: 255,
    previousPrice: 230,
    seasonPoints: 338,
    fantasyPoints: 338,
    tier: 'A' as const,
    isActive: true,
  },
  {
    id: 'sainz',
    name: 'Carlos Sainz Jr.',
    shortName: 'SAI',
    number: 55,
    constructorId: 'williams',
    constructorName: 'Williams Racing',
    nationality: 'Spanish',
    price: 210,
    previousPrice: 200,
    seasonPoints: 272,
    fantasyPoints: 272,
    tier: 'A' as const,
    isActive: true,
  },
  {
    id: 'alonso',
    name: 'Fernando Alonso',
    shortName: 'ALO',
    number: 14,
    constructorId: 'aston_martin',
    constructorName: 'Aston Martin Aramco F1 Team',
    nationality: 'Spanish',
    price: 175,
    previousPrice: 180,
    seasonPoints: 152,
    fantasyPoints: 152,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'perez',
    name: 'Sergio Perez',
    shortName: 'PER',
    number: 11,
    constructorId: 'red_bull',
    constructorName: 'Oracle Red Bull Racing',
    nationality: 'Mexican',
    price: 185,
    previousPrice: 170,
    seasonPoints: 230,
    fantasyPoints: 230,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'antonelli',
    name: 'Kimi Antonelli',
    shortName: 'ANT',
    number: 12,
    constructorId: 'mercedes',
    constructorName: 'Mercedes-AMG Petronas F1 Team',
    nationality: 'Italian',
    price: 145,
    previousPrice: 150,
    seasonPoints: 131,
    fantasyPoints: 131,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'stroll',
    name: 'Lance Stroll',
    shortName: 'STR',
    number: 18,
    constructorId: 'aston_martin',
    constructorName: 'Aston Martin Aramco F1 Team',
    nationality: 'Canadian',
    price: 130,
    previousPrice: 140,
    seasonPoints: 68,
    fantasyPoints: 68,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'gasly',
    name: 'Pierre Gasly',
    shortName: 'GAS',
    number: 10,
    constructorId: 'alpine',
    constructorName: 'BWT Alpine F1 Team',
    nationality: 'French',
    price: 125,
    previousPrice: 130,
    seasonPoints: 42,
    fantasyPoints: 42,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'tsunoda',
    name: 'Yuki Tsunoda',
    shortName: 'TSU',
    number: 22,
    constructorId: 'racing_bulls',
    constructorName: 'Visa Cash App RB F1 Team',
    nationality: 'Japanese',
    price: 130,
    previousPrice: 125,
    seasonPoints: 46,
    fantasyPoints: 46,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'albon',
    name: 'Alexander Albon',
    shortName: 'ALB',
    number: 23,
    constructorId: 'williams',
    constructorName: 'Williams Racing',
    nationality: 'Thai-British',
    price: 115,
    previousPrice: 120,
    seasonPoints: 28,
    fantasyPoints: 28,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'ocon',
    name: 'Esteban Ocon',
    shortName: 'OCO',
    number: 31,
    constructorId: 'haas',
    constructorName: 'MoneyGram Haas F1 Team',
    nationality: 'French',
    price: 110,
    previousPrice: 115,
    seasonPoints: 22,
    fantasyPoints: 22,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'lawson',
    name: 'Liam Lawson',
    shortName: 'LAW',
    number: 30,
    constructorId: 'racing_bulls',
    constructorName: 'Visa Cash App RB F1 Team',
    nationality: 'New Zealander',
    price: 105,
    previousPrice: 110,
    seasonPoints: 18,
    fantasyPoints: 18,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'hulkenberg',
    name: 'Nico Hulkenberg',
    shortName: 'HUL',
    number: 27,
    constructorId: 'sauber',
    constructorName: 'Stake F1 Team Kick Sauber',
    nationality: 'German',
    price: 95,
    previousPrice: 100,
    seasonPoints: 10,
    fantasyPoints: 10,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'doohan',
    name: 'Jack Doohan',
    shortName: 'DOO',
    number: 7,
    constructorId: 'alpine',
    constructorName: 'BWT Alpine F1 Team',
    nationality: 'Australian',
    price: 85,
    previousPrice: 90,
    seasonPoints: 6,
    fantasyPoints: 6,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'bearman',
    name: 'Oliver Bearman',
    shortName: 'BEA',
    number: 87,
    constructorId: 'haas',
    constructorName: 'MoneyGram Haas F1 Team',
    nationality: 'British',
    price: 80,
    previousPrice: 85,
    seasonPoints: 4,
    fantasyPoints: 4,
    tier: 'B' as const,
    isActive: true,
  },
  {
    id: 'bortoleto',
    name: 'Gabriel Bortoleto',
    shortName: 'BOR',
    number: 5,
    constructorId: 'sauber',
    constructorName: 'Stake F1 Team Kick Sauber',
    nationality: 'Brazilian',
    price: 75,
    previousPrice: 80,
    seasonPoints: 2,
    fantasyPoints: 2,
    tier: 'B' as const,
    isActive: true,
  },
];

export const constructors2025 = [
  {
    id: 'mclaren',
    name: 'McLaren F1 Team',
    shortName: 'MCL',
    nationality: 'British',
    primaryColor: '#FF8000',
    secondaryColor: '#47C7FC',
    price: 200,
    previousPrice: 185,
    seasonPoints: 833,
    fantasyPoints: 833,
    drivers: ['norris', 'piastri'],
    isActive: true,
  },
  {
    id: 'mercedes',
    name: 'Mercedes-AMG Petronas F1 Team',
    shortName: 'MER',
    nationality: 'German',
    primaryColor: '#27F4D2',
    secondaryColor: '#000000',
    price: 175,
    previousPrice: 155,
    seasonPoints: 469,
    fantasyPoints: 469,
    drivers: ['russell', 'antonelli'],
    isActive: true,
  },
  {
    id: 'red_bull',
    name: 'Oracle Red Bull Racing',
    shortName: 'RBR',
    nationality: 'Austrian',
    primaryColor: '#3671C6',
    secondaryColor: '#FFD700',
    price: 180,
    previousPrice: 175,
    seasonPoints: 651,
    fantasyPoints: 651,
    drivers: ['verstappen', 'perez'],
    isActive: true,
  },
  {
    id: 'ferrari',
    name: 'Scuderia Ferrari',
    shortName: 'FER',
    nationality: 'Italian',
    primaryColor: '#E80020',
    secondaryColor: '#FFEB00',
    price: 170,
    previousPrice: 180,
    seasonPoints: 398,
    fantasyPoints: 398,
    drivers: ['leclerc', 'hamilton'],
    isActive: true,
  },
  {
    id: 'aston_martin',
    name: 'Aston Martin Aramco F1 Team',
    shortName: 'AMR',
    nationality: 'British',
    primaryColor: '#229971',
    secondaryColor: '#CEDC00',
    price: 115,
    previousPrice: 120,
    seasonPoints: 152,
    fantasyPoints: 152,
    drivers: ['alonso', 'stroll'],
    isActive: true,
  },
  {
    id: 'williams',
    name: 'Williams Racing',
    shortName: 'WIL',
    nationality: 'British',
    primaryColor: '#64C4FF',
    secondaryColor: '#00A3E0',
    price: 105,
    previousPrice: 100,
    seasonPoints: 78,
    fantasyPoints: 78,
    drivers: ['sainz', 'albon'],
    isActive: true,
  },
  {
    id: 'racing_bulls',
    name: 'Visa Cash App RB F1 Team',
    shortName: 'RB',
    nationality: 'Italian',
    primaryColor: '#6692FF',
    secondaryColor: '#1E5BC6',
    price: 90,
    previousPrice: 85,
    seasonPoints: 64,
    fantasyPoints: 64,
    drivers: ['tsunoda', 'lawson'],
    isActive: true,
  },
  {
    id: 'alpine',
    name: 'BWT Alpine F1 Team',
    shortName: 'ALP',
    nationality: 'French',
    primaryColor: '#FF87BC',
    secondaryColor: '#0093CC',
    price: 80,
    previousPrice: 90,
    seasonPoints: 48,
    fantasyPoints: 48,
    drivers: ['gasly', 'doohan'],
    isActive: true,
  },
  {
    id: 'haas',
    name: 'MoneyGram Haas F1 Team',
    shortName: 'HAA',
    nationality: 'American',
    primaryColor: '#B6BABD',
    secondaryColor: '#E10600',
    price: 70,
    previousPrice: 75,
    seasonPoints: 26,
    fantasyPoints: 26,
    drivers: ['ocon', 'bearman'],
    isActive: true,
  },
  {
    id: 'sauber',
    name: 'Stake F1 Team Kick Sauber',
    shortName: 'SAU',
    nationality: 'Swiss',
    primaryColor: '#52E252',
    secondaryColor: '#000000',
    price: 55,
    previousPrice: 60,
    seasonPoints: 12,
    fantasyPoints: 12,
    drivers: ['hulkenberg', 'bortoleto'],
    isActive: true,
  },
];

// Race results for completed races
export const raceResults2025 = {
  australia_2025: {
    race: [
      { driverId: 'norris', position: 1, points: 25 },
      { driverId: 'verstappen', position: 2, points: 18 },
      { driverId: 'russell', position: 3, points: 15 },
      { driverId: 'piastri', position: 4, points: 12 },
      { driverId: 'leclerc', position: 5, points: 10 },
      { driverId: 'hamilton', position: 6, points: 8 },
      { driverId: 'sainz', position: 7, points: 6 },
      { driverId: 'perez', position: 8, points: 4 },
      { driverId: 'alonso', position: 9, points: 2 },
      { driverId: 'stroll', position: 10, points: 1 },
    ],
  },
  china_2025: {
    race: [
      { driverId: 'piastri', position: 1, points: 25 },
      { driverId: 'norris', position: 2, points: 18 },
      { driverId: 'russell', position: 3, points: 15 },
      { driverId: 'verstappen', position: 4, points: 12 },
      { driverId: 'leclerc', position: 5, points: 10 },
      { driverId: 'hamilton', position: 6, points: 8 },
      { driverId: 'sainz', position: 7, points: 6 },
      { driverId: 'perez', position: 8, points: 4 },
      { driverId: 'alonso', position: 9, points: 2 },
      { driverId: 'stroll', position: 10, points: 1 },
    ],
  },
  japan_2025: {
    race: [
      { driverId: 'verstappen', position: 1, points: 25 },
      { driverId: 'norris', position: 2, points: 18 },
      { driverId: 'piastri', position: 3, points: 15 },
      { driverId: 'leclerc', position: 4, points: 12 },
      { driverId: 'russell', position: 5, points: 10 },
      { driverId: 'hamilton', position: 6, points: 8 },
      { driverId: 'sainz', position: 7, points: 6 },
      { driverId: 'perez', position: 8, points: 4 },
      { driverId: 'alonso', position: 9, points: 2 },
      { driverId: 'tsunoda', position: 10, points: 1 },
    ],
  },
};

export const races2025 = [
  {
    id: 'australia_2025',
    seasonId: '2025',
    round: 1,
    name: 'Australian Grand Prix',
    officialName: 'Formula 1 Rolex Australian Grand Prix 2025',
    circuitId: 'albert_park',
    circuitName: 'Albert Park Circuit',
    country: 'Australia',
    city: 'Melbourne',
    timezone: 'Australia/Melbourne',
    hasSprint: false,
    status: 'completed' as const,
    schedule: {
      fp1: new Date('2025-03-14T01:30:00Z'),
      fp2: new Date('2025-03-14T05:00:00Z'),
      fp3: new Date('2025-03-15T01:30:00Z'),
      qualifying: new Date('2025-03-15T05:00:00Z'),
      race: new Date('2025-03-16T04:00:00Z'),
    },
    results: raceResults2025.australia_2025,
  },
  {
    id: 'china_2025',
    seasonId: '2025',
    round: 2,
    name: 'Chinese Grand Prix',
    officialName: 'Formula 1 Lenovo Chinese Grand Prix 2025',
    circuitId: 'shanghai',
    circuitName: 'Shanghai International Circuit',
    country: 'China',
    city: 'Shanghai',
    timezone: 'Asia/Shanghai',
    hasSprint: true,
    status: 'completed' as const,
    schedule: {
      fp1: new Date('2025-03-21T03:30:00Z'),
      sprintQualifying: new Date('2025-03-21T07:30:00Z'),
      sprint: new Date('2025-03-22T03:00:00Z'),
      qualifying: new Date('2025-03-22T07:00:00Z'),
      race: new Date('2025-03-23T07:00:00Z'),
    },
    results: raceResults2025.china_2025,
  },
  {
    id: 'japan_2025',
    seasonId: '2025',
    round: 3,
    name: 'Japanese Grand Prix',
    officialName: 'Formula 1 Lenovo Japanese Grand Prix 2025',
    circuitId: 'suzuka',
    circuitName: 'Suzuka International Racing Course',
    country: 'Japan',
    city: 'Suzuka',
    timezone: 'Asia/Tokyo',
    hasSprint: false,
    status: 'completed' as const,
    schedule: {
      fp1: new Date('2025-04-04T02:30:00Z'),
      fp2: new Date('2025-04-04T06:00:00Z'),
      fp3: new Date('2025-04-05T02:30:00Z'),
      qualifying: new Date('2025-04-05T06:00:00Z'),
      race: new Date('2025-04-06T05:00:00Z'),
    },
    results: raceResults2025.japan_2025,
  },
  {
    id: 'bahrain_2025',
    seasonId: '2025',
    round: 4,
    name: 'Bahrain Grand Prix',
    officialName: 'Formula 1 Gulf Air Bahrain Grand Prix 2025',
    circuitId: 'bahrain',
    circuitName: 'Bahrain International Circuit',
    country: 'Bahrain',
    city: 'Sakhir',
    timezone: 'Asia/Bahrain',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-04-11T11:30:00Z'),
      fp2: new Date('2025-04-11T15:00:00Z'),
      fp3: new Date('2025-04-12T12:30:00Z'),
      qualifying: new Date('2025-04-12T16:00:00Z'),
      race: new Date('2025-04-13T15:00:00Z'),
    },
  },
  {
    id: 'saudi_2025',
    seasonId: '2025',
    round: 5,
    name: 'Saudi Arabian Grand Prix',
    officialName: 'Formula 1 STC Saudi Arabian Grand Prix 2025',
    circuitId: 'jeddah',
    circuitName: 'Jeddah Corniche Circuit',
    country: 'Saudi Arabia',
    city: 'Jeddah',
    timezone: 'Asia/Riyadh',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-04-18T13:30:00Z'),
      fp2: new Date('2025-04-18T17:00:00Z'),
      fp3: new Date('2025-04-19T13:30:00Z'),
      qualifying: new Date('2025-04-19T17:00:00Z'),
      race: new Date('2025-04-20T17:00:00Z'),
    },
  },
  {
    id: 'miami_2025',
    seasonId: '2025',
    round: 6,
    name: 'Miami Grand Prix',
    officialName: 'Formula 1 Crypto.com Miami Grand Prix 2025',
    circuitId: 'miami',
    circuitName: 'Miami International Autodrome',
    country: 'United States',
    city: 'Miami',
    timezone: 'America/New_York',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-05-02T18:30:00Z'),
      sprintQualifying: new Date('2025-05-02T22:30:00Z'),
      sprint: new Date('2025-05-03T16:00:00Z'),
      qualifying: new Date('2025-05-03T20:00:00Z'),
      race: new Date('2025-05-04T20:00:00Z'),
    },
  },
  {
    id: 'emilia_romagna_2025',
    seasonId: '2025',
    round: 7,
    name: 'Emilia Romagna Grand Prix',
    officialName: 'Formula 1 MSC Cruises Emilia Romagna Grand Prix 2025',
    circuitId: 'imola',
    circuitName: 'Autodromo Enzo e Dino Ferrari',
    country: 'Italy',
    city: 'Imola',
    timezone: 'Europe/Rome',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-05-16T11:30:00Z'),
      fp2: new Date('2025-05-16T15:00:00Z'),
      fp3: new Date('2025-05-17T10:30:00Z'),
      qualifying: new Date('2025-05-17T14:00:00Z'),
      race: new Date('2025-05-18T13:00:00Z'),
    },
  },
  {
    id: 'monaco_2025',
    seasonId: '2025',
    round: 8,
    name: 'Monaco Grand Prix',
    officialName: 'Formula 1 Grand Prix de Monaco 2025',
    circuitId: 'monaco',
    circuitName: 'Circuit de Monaco',
    country: 'Monaco',
    city: 'Monte Carlo',
    timezone: 'Europe/Monaco',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-05-23T11:30:00Z'),
      fp2: new Date('2025-05-23T15:00:00Z'),
      fp3: new Date('2025-05-24T10:30:00Z'),
      qualifying: new Date('2025-05-24T14:00:00Z'),
      race: new Date('2025-05-25T13:00:00Z'),
    },
  },
  {
    id: 'spain_2025',
    seasonId: '2025',
    round: 9,
    name: 'Spanish Grand Prix',
    officialName: 'Formula 1 Aramco Gran Premio de Espana 2025',
    circuitId: 'barcelona',
    circuitName: 'Circuit de Barcelona-Catalunya',
    country: 'Spain',
    city: 'Barcelona',
    timezone: 'Europe/Madrid',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-05-30T11:30:00Z'),
      fp2: new Date('2025-05-30T15:00:00Z'),
      fp3: new Date('2025-05-31T10:30:00Z'),
      qualifying: new Date('2025-05-31T14:00:00Z'),
      race: new Date('2025-06-01T13:00:00Z'),
    },
  },
  {
    id: 'canada_2025',
    seasonId: '2025',
    round: 10,
    name: 'Canadian Grand Prix',
    officialName: 'Formula 1 AWS Grand Prix du Canada 2025',
    circuitId: 'montreal',
    circuitName: 'Circuit Gilles Villeneuve',
    country: 'Canada',
    city: 'Montreal',
    timezone: 'America/Toronto',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-06-13T17:30:00Z'),
      fp2: new Date('2025-06-13T21:00:00Z'),
      fp3: new Date('2025-06-14T16:30:00Z'),
      qualifying: new Date('2025-06-14T20:00:00Z'),
      race: new Date('2025-06-15T18:00:00Z'),
    },
  },
  {
    id: 'austria_2025',
    seasonId: '2025',
    round: 11,
    name: 'Austrian Grand Prix',
    officialName: 'Formula 1 Rolex Grosser Preis von Osterreich 2025',
    circuitId: 'red_bull_ring',
    circuitName: 'Red Bull Ring',
    country: 'Austria',
    city: 'Spielberg',
    timezone: 'Europe/Vienna',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-06-27T11:30:00Z'),
      fp2: new Date('2025-06-27T15:00:00Z'),
      fp3: new Date('2025-06-28T10:30:00Z'),
      qualifying: new Date('2025-06-28T14:00:00Z'),
      race: new Date('2025-06-29T13:00:00Z'),
    },
  },
  {
    id: 'britain_2025',
    seasonId: '2025',
    round: 12,
    name: 'British Grand Prix',
    officialName: 'Formula 1 Qatar Airways British Grand Prix 2025',
    circuitId: 'silverstone',
    circuitName: 'Silverstone Circuit',
    country: 'United Kingdom',
    city: 'Silverstone',
    timezone: 'Europe/London',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-07-04T11:30:00Z'),
      fp2: new Date('2025-07-04T15:00:00Z'),
      fp3: new Date('2025-07-05T10:30:00Z'),
      qualifying: new Date('2025-07-05T14:00:00Z'),
      race: new Date('2025-07-06T14:00:00Z'),
    },
  },
  {
    id: 'belgium_2025',
    seasonId: '2025',
    round: 13,
    name: 'Belgian Grand Prix',
    officialName: 'Formula 1 Rolex Belgian Grand Prix 2025',
    circuitId: 'spa',
    circuitName: 'Circuit de Spa-Francorchamps',
    country: 'Belgium',
    city: 'Spa',
    timezone: 'Europe/Brussels',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-07-25T11:30:00Z'),
      sprintQualifying: new Date('2025-07-25T15:30:00Z'),
      sprint: new Date('2025-07-26T11:00:00Z'),
      qualifying: new Date('2025-07-26T15:00:00Z'),
      race: new Date('2025-07-27T13:00:00Z'),
    },
  },
  {
    id: 'hungary_2025',
    seasonId: '2025',
    round: 14,
    name: 'Hungarian Grand Prix',
    officialName: 'Formula 1 Lenovo Hungarian Grand Prix 2025',
    circuitId: 'hungaroring',
    circuitName: 'Hungaroring',
    country: 'Hungary',
    city: 'Budapest',
    timezone: 'Europe/Budapest',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-08-01T11:30:00Z'),
      fp2: new Date('2025-08-01T15:00:00Z'),
      fp3: new Date('2025-08-02T10:30:00Z'),
      qualifying: new Date('2025-08-02T14:00:00Z'),
      race: new Date('2025-08-03T13:00:00Z'),
    },
  },
  {
    id: 'netherlands_2025',
    seasonId: '2025',
    round: 15,
    name: 'Dutch Grand Prix',
    officialName: 'Formula 1 Heineken Dutch Grand Prix 2025',
    circuitId: 'zandvoort',
    circuitName: 'Circuit Zandvoort',
    country: 'Netherlands',
    city: 'Zandvoort',
    timezone: 'Europe/Amsterdam',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-08-29T10:30:00Z'),
      fp2: new Date('2025-08-29T14:00:00Z'),
      fp3: new Date('2025-08-30T09:30:00Z'),
      qualifying: new Date('2025-08-30T13:00:00Z'),
      race: new Date('2025-08-31T13:00:00Z'),
    },
  },
  {
    id: 'italy_2025',
    seasonId: '2025',
    round: 16,
    name: 'Italian Grand Prix',
    officialName: 'Formula 1 Pirelli Gran Premio dItalia 2025',
    circuitId: 'monza',
    circuitName: 'Autodromo Nazionale Monza',
    country: 'Italy',
    city: 'Monza',
    timezone: 'Europe/Rome',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-09-05T11:30:00Z'),
      fp2: new Date('2025-09-05T15:00:00Z'),
      fp3: new Date('2025-09-06T10:30:00Z'),
      qualifying: new Date('2025-09-06T14:00:00Z'),
      race: new Date('2025-09-07T13:00:00Z'),
    },
  },
  {
    id: 'azerbaijan_2025',
    seasonId: '2025',
    round: 17,
    name: 'Azerbaijan Grand Prix',
    officialName: 'Formula 1 Qatar Airways Azerbaijan Grand Prix 2025',
    circuitId: 'baku',
    circuitName: 'Baku City Circuit',
    country: 'Azerbaijan',
    city: 'Baku',
    timezone: 'Asia/Baku',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-09-19T09:30:00Z'),
      fp2: new Date('2025-09-19T13:00:00Z'),
      fp3: new Date('2025-09-20T08:30:00Z'),
      qualifying: new Date('2025-09-20T12:00:00Z'),
      race: new Date('2025-09-21T11:00:00Z'),
    },
  },
  {
    id: 'singapore_2025',
    seasonId: '2025',
    round: 18,
    name: 'Singapore Grand Prix',
    officialName: 'Formula 1 Singapore Airlines Singapore Grand Prix 2025',
    circuitId: 'marina_bay',
    circuitName: 'Marina Bay Street Circuit',
    country: 'Singapore',
    city: 'Singapore',
    timezone: 'Asia/Singapore',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-10-03T09:30:00Z'),
      fp2: new Date('2025-10-03T13:00:00Z'),
      fp3: new Date('2025-10-04T09:30:00Z'),
      qualifying: new Date('2025-10-04T13:00:00Z'),
      race: new Date('2025-10-05T12:00:00Z'),
    },
  },
  {
    id: 'usa_2025',
    seasonId: '2025',
    round: 19,
    name: 'United States Grand Prix',
    officialName: 'Formula 1 Pirelli United States Grand Prix 2025',
    circuitId: 'cota',
    circuitName: 'Circuit of the Americas',
    country: 'United States',
    city: 'Austin',
    timezone: 'America/Chicago',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-10-17T17:30:00Z'),
      sprintQualifying: new Date('2025-10-17T21:30:00Z'),
      sprint: new Date('2025-10-18T18:00:00Z'),
      qualifying: new Date('2025-10-18T22:00:00Z'),
      race: new Date('2025-10-19T19:00:00Z'),
    },
  },
  {
    id: 'mexico_2025',
    seasonId: '2025',
    round: 20,
    name: 'Mexico City Grand Prix',
    officialName: 'Formula 1 Gran Premio de la Ciudad de Mexico 2025',
    circuitId: 'hermanos_rodriguez',
    circuitName: 'Autodromo Hermanos Rodriguez',
    country: 'Mexico',
    city: 'Mexico City',
    timezone: 'America/Mexico_City',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-10-24T18:30:00Z'),
      fp2: new Date('2025-10-24T22:00:00Z'),
      fp3: new Date('2025-10-25T17:30:00Z'),
      qualifying: new Date('2025-10-25T21:00:00Z'),
      race: new Date('2025-10-26T20:00:00Z'),
    },
  },
  {
    id: 'brazil_2025',
    seasonId: '2025',
    round: 21,
    name: 'Sao Paulo Grand Prix',
    officialName: 'Formula 1 Lenovo Grande Premio de Sao Paulo 2025',
    circuitId: 'interlagos',
    circuitName: 'Autodromo Jose Carlos Pace',
    country: 'Brazil',
    city: 'Sao Paulo',
    timezone: 'America/Sao_Paulo',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-11-07T14:30:00Z'),
      sprintQualifying: new Date('2025-11-07T18:30:00Z'),
      sprint: new Date('2025-11-08T14:00:00Z'),
      qualifying: new Date('2025-11-08T18:00:00Z'),
      race: new Date('2025-11-09T17:00:00Z'),
    },
  },
  {
    id: 'las_vegas_2025',
    seasonId: '2025',
    round: 22,
    name: 'Las Vegas Grand Prix',
    officialName: 'Formula 1 Heineken Silver Las Vegas Grand Prix 2025',
    circuitId: 'las_vegas',
    circuitName: 'Las Vegas Strip Circuit',
    country: 'United States',
    city: 'Las Vegas',
    timezone: 'America/Los_Angeles',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-11-21T02:30:00Z'),
      fp2: new Date('2025-11-21T06:00:00Z'),
      fp3: new Date('2025-11-22T02:30:00Z'),
      qualifying: new Date('2025-11-22T06:00:00Z'),
      race: new Date('2025-11-23T06:00:00Z'),
    },
  },
  {
    id: 'qatar_2025',
    seasonId: '2025',
    round: 23,
    name: 'Qatar Grand Prix',
    officialName: 'Formula 1 Qatar Airways Qatar Grand Prix 2025',
    circuitId: 'lusail',
    circuitName: 'Lusail International Circuit',
    country: 'Qatar',
    city: 'Lusail',
    timezone: 'Asia/Qatar',
    hasSprint: true,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-11-28T13:30:00Z'),
      sprintQualifying: new Date('2025-11-28T17:30:00Z'),
      sprint: new Date('2025-11-29T14:00:00Z'),
      qualifying: new Date('2025-11-29T18:00:00Z'),
      race: new Date('2025-11-30T17:00:00Z'),
    },
  },
  {
    id: 'abu_dhabi_2025',
    seasonId: '2025',
    round: 24,
    name: 'Abu Dhabi Grand Prix',
    officialName: 'Formula 1 Etihad Airways Abu Dhabi Grand Prix 2025',
    circuitId: 'yas_marina',
    circuitName: 'Yas Marina Circuit',
    country: 'United Arab Emirates',
    city: 'Abu Dhabi',
    timezone: 'Asia/Dubai',
    hasSprint: false,
    status: 'upcoming' as const,
    schedule: {
      fp1: new Date('2025-12-05T09:30:00Z'),
      fp2: new Date('2025-12-05T13:00:00Z'),
      fp3: new Date('2025-12-06T10:30:00Z'),
      qualifying: new Date('2025-12-06T14:00:00Z'),
      race: new Date('2025-12-07T13:00:00Z'),
    },
  },
];

export const season2025 = {
  id: '2025',
  year: 2025,
  name: 'F1 2025 Season',
  isActive: true,
  startDate: new Date('2025-03-14'),
  endDate: new Date('2025-12-07'),
  totalRaces: 24,
  currentRound: 4, // Next race is Bahrain (round 4)
  budget: 1000,
  teamSize: 5,
  scoringRules: {
    racePoints: [25, 18, 15, 12, 10, 8, 6, 4, 2, 1],
    sprintPoints: [8, 7, 6, 5, 4, 3, 2, 1],
    fastestLapBonus: 1,
    positionGainedBonus: 1,
    qualifyingPoints: [],
    dnfPenalty: 0,
    dsqPenalty: -5,
  },
  pricingRules: {
    greatPPMThreshold: 0.8,
    goodPPMThreshold: 0.6,
    poorPPMThreshold: 0.4,
    aTierPriceChange: { great: 15, good: 5, poor: -5, terrible: -15 },
    bTierPriceChange: { great: 10, good: 3, poor: -3, terrible: -10 },
  },
};

// Championship standings (for display)
export const driverStandings2025 = [
  { position: 1, driverId: 'norris', points: 423 },
  { position: 2, driverId: 'verstappen', points: 421 },
  { position: 3, driverId: 'piastri', points: 410 },
  { position: 4, driverId: 'leclerc', points: 356 },
  { position: 5, driverId: 'russell', points: 338 },
  { position: 6, driverId: 'hamilton', points: 289 },
  { position: 7, driverId: 'sainz', points: 272 },
  { position: 8, driverId: 'perez', points: 230 },
  { position: 9, driverId: 'alonso', points: 152 },
  { position: 10, driverId: 'antonelli', points: 131 },
];

export const constructorStandings2025 = [
  { position: 1, constructorId: 'mclaren', points: 833 },
  { position: 2, constructorId: 'red_bull', points: 651 },
  { position: 3, constructorId: 'mercedes', points: 469 },
  { position: 4, constructorId: 'ferrari', points: 398 },
  { position: 5, constructorId: 'aston_martin', points: 152 },
  { position: 6, constructorId: 'williams', points: 78 },
  { position: 7, constructorId: 'racing_bulls', points: 64 },
  { position: 8, constructorId: 'alpine', points: 48 },
  { position: 9, constructorId: 'haas', points: 26 },
  { position: 10, constructorId: 'sauber', points: 12 },
];

console.log('2025 Season Seed Data Ready (with race results)');
console.log(`Drivers: ${drivers2025.length}`);
console.log(`Constructors: ${constructors2025.length}`);
console.log(`Races: ${races2025.length}`);
console.log(`Completed Races: ${races2025.filter(r => r.status === 'completed').length}`);
